server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_fridge_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: olexandrkuzmenkov16@gmail.com
    password: jbgqlbtokxeiriqi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true